# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: >-
        mvn -B 
        clean 
        package 
        -Pnative 
        -Dquarkus.container-image.build=true 
        -Dquarkus.container-image.push=true
        -Dquarkus.container-image.group=galaxy102
        -Dquarkus.container-image.additional-tags=latest
        -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }}
        -Dquarkus.container-image.password=${{ secrets.DOCKER_PASSWORD }}
        --file pom.xml
